<?php
$arr = [
  "Home",
  "Confirm Password",
  "Password",
  "current-password",
  "Update Password",
  "Forgot Your Password",
  "Recover Password",
  "Reset Password",
  "status",
  "Identity Type",
  "Our Pricing",
  "Enter Your Email address",
  "submit",
  "Unlimited",
  "Email address",
  "Enter New Password",
  "Submit",
  "New Password",
  "Create New Ticket",
  "Send Password Reset Link",
  "Don't have any account? Sign Up",
  "Code",
  "Didn\'t get Code? Click to",
  "Resend code",
  "resend",
  "Sign In",
  "sign in",
  "search date",
  "Login here",
  "Email Or Username",
  "Remember me",
  "Forgot password",
  "Don't have an account?",
  "Create account",
  "Sign Up",
  "register here",
  "Register",
  "First name",
  "Payment History",
  "Last name",
  "Username",
  "Email Address",
  "Phone Number",
  "Already Purchased",
  "Already have an account?",
  "Email Verify",
  "Verify Your Email Address",
  "A fresh verification link has been sent to your email address.",
  "Before proceeding, please check your email for a verification link.",
  "If you did not receive the email",
  "click here to request another",
  "403 Forbidden",
  "Forbidden",
  "You don't have permission to access ‘/’ on this server",
  "Back To Home",
  "404",
  "not found",
  "Oops!",
  "We can't seem to find the page you are looking for",
  "405",
  "Method Not Allowed",
  "419",
  "Sorry, your session has expired",
  "Listings",
  "Profile",
  "Change Password",
  "Total Listings",
  "logout",
  "Sign Out",
  "Dashboard",
  "My Packages",
  "My Listings",
  "WishList",
  "Product Enquiry",
  "Transaction",
  "Analytics",
  "support ticket",
  "Privacy Policy",
  "Active Listings",
  "Pending Listings",
  "Accept",
  "Ticket",
  "Last Reply",
  "Decline",
  "Quick Links",
  "About",
  "Pricing",
  "Listing",
  "Blogs",
  "Contact",
  "OUR Services",
  "FAQ",
  "get in touch",
  "All Rights Reserved",
  "Copyright ",
  "Category",
  "What are you looking for",
  "Location",
  "Categories",
  "search",
  "Sign in",
  "Contact Us",
  "Search",
  "Full name",
  "success",
  "error",
  "warning",
  "Previous",
  "Next",
  "Clear all",
  "You have no notifications",
  "views",
  "Views",
  "reviews",
  "Reviews",
  "review",
  "view details",
  "Website:",
  "Preferred language",
  "Image Missing",
  "Select Language",
  "Explore more",
  "No Data Found",
  "Popular listings",
  "Explore the greates places in the city. You won’t be disappointed.",
  "view all",
  "Blog Details",
  "Enter Email Address",
  "subscribe",
  "Pay with",
  "Enter your card number",
  "Enter the name on your card",
  "Uh-ho! We are unable to process your Payment by this method. This method is under construction!!",
  "as your payment method.",
  "bkash",
  "Select",
  "Payment Preview",
  "PLEASE SEND EXACTLY",
  "TO",
  "SCAN TO SEND",
  "Payment Confirm",
  "Pay Now",
  "Please follow the instruction below",
  "You have requested to deposit",
  "Please pay",
  "for successful payment",
  "Change",
  "Remove",
  "Your KYC submission has been pending",
  "Your KYC already verified",
  "You previous request has been rejected",
  "Confirm Now",
  "Address Proof",
  "Pay via Monnify",
  "Pay with VoguePay",
  "Type Here",
  "All Payment",
  "Pending Payment",
  "Complete Payment",
  "Rejected Payment",
  "Transaction ID",
  "Gateway",
  "Amount",
  "Charge",
  "Status",
  "Time",
  "Detail",
  "Pending",
  "Complete",
  "Cancel",
  "No Data Found!",
  "Details",
  "Transactions",
  "Admin Feedback",
  "Close",
  "'Payment Information",
  "PAYOUT NOW",
  "Request Amount",
  "Charge Amount",
  "otal Payable",
  "Available Balance",
  "Additional Information To Withdraw Confirm",
  "Profile Settings",
  "Settings",
  "Joined",
  "Follower",
  "follow",
  "unFollow",
  "No Followers",
  "No Followings",
  "Copy profile",
  "Following",
  "Your Card Information",
  "Basic Info",
  "Address",
  "Profile information",
  "Password setting",
  "identity verification",
  "address verification",
  "Bio",
  "First Name",
  "Last Name",
  "Social Links",
  "Facebook",
  "Instagram",
  "Twitter",
  "Whatsapp",
  "LinkedIn",
  "choose icon",
  "URL",
  "Enter Current Password",
  "Current Password",
  "Submit changes",
  "Confirmation",
  "Save changes",
  "Subject",
  "Message",
  "Upload File",
  "Enter Subject",
  "Enter Message",
  "My Tickets",
  "ticket no.",
  "Cancelled",
  "Approved",
  "Create Ticket",
  "Action",
  "Open",
  "2 Step Security",
  "Answered",
  "Replied",
  "Closed",
  "Delete Confirmation",
  "Are you sure delete?",
  "Yes",
  "No",
  "Customer Reply",
  "Image Upload",
  "Reply",
  "File",
  "Are you want to close ticket?",
  "Cancel Payment",
  "My Transaction",
  "Search for Transaction ID",
  "Remark",
  "Payment Method",
  "Remarks",
  "Date-Time",
  "My Payment History",
  "Payment History For",
  "Two Factor Authenticator",
  "Disable Two Factor Authenticator",
  "Enable Two Factor Authenticator",
  "Google Authenticator",
  "Use Google Authenticator to Scan the QR code  or use the code",
  "Google Authenticator is a multifactor app for mobile devices. It generates timed codes used during the 2-step verification process. To use Google Authenticator, ▶",
  "DOWNLOAD APP",
  "Add Fund",
  "Transaction Limit:",
  "Charge:",
  "Payment By",
  "Payable",
  "Conversion Rate",
  "All Listing",
  "Video",
  "Photos",
  "Amenities",
  "Products",
  "Unseen Enquiries",
  "Product",
  "Active Package",
  "Pending Package",
  "Title",
  "Select Category",
  "Email",
  "Phone",
  "Privacy & Policy",
  "description",
  "Select Place",
  "Search Location",
  "Search Listing",
  "Lat",
  "Long",
  "You can also set location moving marker",
  "Business Hours",
  "Satureday",
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Youtube Video Id",
  "Thumbnail",
  "Select Image",
  "Images",
  "Click to Upload photos",
  "unlimited",
  "Product Thumbnail",
  "keywords",
  "My Analytics",
  "Search listing...",
  "Added At",
  "Verification",
  "Email Verification",
  "All Listing & Contact Message",
  "Contact Messages",
  "Active",
  "Expired",
  "Name",
  "From",
  "Delete",
  "Followers",
  "Visit profile",
  "Upcoming Expired Packages",
  "Used",
  "Infinity",
  "selected",
  "Package",
  "Listing Category",
  "Rejected",
  "Edit",
  "Add More",
  "SEO & META Keywords",
  "SEO",
  "No more add products",
  "Select Package",
  "Enter Location",
  "Add Listing",
  "Stage ",
  "Deactive",
  "Create Listing",
  "No. of available listing",
  "Make Query",
  "Create",
  "Payment option",
  "Make payment",
  "Choose How You Want To Pay",
  "Select Payment Method",
  "Select Payment",
  "Price",
  "Conversation Rate",
  "Percentage Charge",
  "Fixed Charge",
  "Total Amount",
  "Search Package",
  "No. of listing",
  "Purchased Date",
  "purchased date",
  "Expired Date",
  "Validity",
  "Cencel",
  "No. Of Listing",
  "Renew Package",
  "Package Renew Information",
  "Confirm",
  "Plan Name",
  "Product Enquiries",
  "Customer Enquiry",
  "No message available here",
  "My Enquiry",
  "Search Here...",
  "Customer",
  "Vendor",
  "All Transactions",
  "Send reply",
  "Product query reply",
  "is typing...",
  "Type your message...",
  "Your message",
  "Product Information",
  "+Not Found",
  "Customer Information",
  "Visit Profile",
  "Owner Information",
  "My WishList",
  "About Us",
  "All Listings",
  "Listing name",
  "Select Location",
  "Select category",
  "All Category",
  "Select User",
  "All User",
  "All Location",
  "Filter by Ratings",
  "View details",
  "Wishlist removed",
  "Listing Details",
  "No Review Found",
  "Add Review",
  "Description",
  "Login to review",
  "Writing great reviews may help others discover the places that are just apt for them",
  "Submit now",
  "Latest Listings",
  "Created By",
  "Member since",
  "Opening Hours",
  "Contact Seller",
  "Send a Message",
  "Full Name",
  "Claim This Business",
  "Claim",
  "Claim Business",
  "Our Best Pricing",
  "Package expiry",
  "No of Listing",
  "No of images per listing",
  "No of Product",
  "No of images per product",
  "No of amenities per listing",
  "choose plan",
  "Purchase Plan Information",
  "Purchase Now",
  "Total Views",
  "Contact Creator",
  "send",
  "Listings By",
  "No Ratings",
  "We really appreciate you giving us a moment of your time today but unfortunately the payment was unsuccessful due",
  "Go back to Home",
  "it seems some issue in server to server communication. Kindly connect with administrator",
  "THANK YOU!",
  "Thanks a bunch for filling that out. It means a lot to us, just like you do! We really appreciate you giving us a moment of your time today. Thanks for being wi ▶",
  "if you get 500(server error) for some reason, please turn on and try again. Then you can see what was missing in your system.",
  "Pull up or down the rows to sort the ranking list order that how do you want to display the ranking in admin and user panel.",
  "From date",
  "After changes logo/seo. Please clear your browser\'s cache to see changes.",
  "To date",
  "Country ",
  "City",
  "Listing Analytics",
  "Visitor IP",
  "Browser",
  "Total Visit",
  "Last Visited At",
  "Are you sure delete message?",
  "Payment Status",
  "Operatin System",
  "Visited At",
  "My Plan",
  "TRX",
  "No.",
];
return $arr;
